server:
  port: 8081

spring:
  application:
    name: ms-app
  datasource:
    url: jdbc:mysql://localhost:3306/microservices_example
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        legacy_limit_handler: true
        dialect: org.hibernate.dialect.MySQL55Dialect
    hibernate:
      ddl-auto: update

logging:
  level:
    org:hibernate: DEBUG
    org.springframework.security: debug
    
ribbon:
  ConnectTimeout: 15000
  ReadTimeout: 300000
  SocketTimeout: 300000
  maxAutoRetries: 1
  MaxAutoRetriesNextServer: 2
  eager-load:
    enabled: true
    
gateway:
  ribbon:
    listOfServers: http://localhost:8082
    
report:
  ribbon:
    listOfServers: http://localhost:8083